[build]
  functions = "netlify/functions" # Path to your serverless PHP functions
  publish = "." # The folder to publish, set it as the root

[context.production.environment]
  # Any environment variables you want to set for the PHP functions
