[build]
  functions = "netlify/functions" # Directory with PHP serverless functions
  publish = "."  # Use the root directory instead of 'public'


[context.production.environment]
  NODE_VERSION = "16" # Optional, specify the node version
